import type { Preset } from "../types/preset";

export const IDENTITY_PRESET: Omit<Preset, "id" | "name" | "description"> = {
  brightness: 1,
  contrast: 1,
  saturation: 1,
  blur: 0,
  grain: 0,
  bloom: 0,
  warmth: 0,
  fade: 0,
};

export const presets: Preset[] = [
  {
    id: "summer",
    name: "Summer",
    description: "夏の夕方、古いデジカメの残像",
    brightness: 1.12,
    contrast: 1.05,
    saturation: 1.22,
    blur: 0.4,
    grain: 0.18,
    bloom: 0.28,
    warmth: 0.55,
    fade: 0.12,
  },
  {
    id: "dream",
    name: "Dream",
    description: "輪郭が溶ける、夢の中の光",
    brightness: 1.1,
    contrast: 0.86,
    saturation: 0.92,
    blur: 2.4,
    grain: 0.06,
    bloom: 0.42,
    warmth: 0.12,
    fade: 0.18,
  },
  {
    id: "film",
    name: "Film",
    description: "フィルムに焼きついた静けさ",
    brightness: 1.02,
    contrast: 0.88,
    saturation: 0.78,
    blur: 0.2,
    grain: 0.32,
    bloom: 0.1,
    warmth: 0.22,
    fade: 0.34,
  },
  {
    id: "night",
    name: "Night",
    description: "夜の街が滲むブルー",
    brightness: 0.96,
    contrast: 1.22,
    saturation: 1.08,
    blur: 1.1,
    grain: 0.14,
    bloom: 0.36,
    warmth: -0.48,
    fade: 0.08,
  },
  {
    id: "memory",
    name: "Memory",
    description: "色褪せた、引き出しの奥の一枚",
    brightness: 1.04,
    contrast: 0.9,
    saturation: 0.72,
    blur: 1.4,
    grain: 0.26,
    bloom: 0.16,
    warmth: 0.38,
    fade: 0.4,
  },
];

export const DEFAULT_PRESET_ID = "memory";
